jobs:
  - job: general_build_test
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - checkout: self
      clean: true
    - script: |
        npm ci
      displayName: 'npm install'
    - script: |
        npm run test:coverage
      displayName: 'npm run test'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
      displayName: 'publish codes coverages'
    - script: |
        npm run build
      displayName: 'npm run build'
    - task: CopyFiles@2
      displayname: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
          Contents: |
            **/*
            !coverage/**/*
            !.azurepipeline/**/*
            !.git/**/*
          TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishbuildArtifacts@1
      inputs:
        pathtopublish: $(Build.ArtifactStagingDirectory)
        publishLocation: Container


