jobs:
  - job: build and test
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - checkout: self
      clean: true
    - script: |
        npm ci
      displayName: 'npm install'
    - script: |
        npm run test:coverage
      displayName: 'npm run test'
    - script: |
        npm run test:coverage
      displayName: 'npm run test'
    - script: |
        npm run build
      displayName: 'npm run build'

