jobs:
  - deployment: publish_staging_package
    pool:
      vmImage: 'ubuntu-18.04'
    dependsOn: general_build_test
    condition: succeeded()
    strategy:
      runOnce:
        deploy:
          steps:
            - task: NodeTool@0
              inputs:
                versionSpec: '12.x'
              displayName: 'Install Node.js'
            - checkout: self
              clean: true
            - script: |
                npm ci
              displayName: 'npm install'
            - script: 'npm run release-beta'
              displayName: 'publish beta version'
